route:
  group_by: ['alertname']
  group_wait: 5m
  group_interval: 15m
  repeat_interval: 2h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: ${EMAIL}
        from: ${EMAIL}
        smarthost: ${SMTP_SERVER}
        auth_username: ${SMTP_USERNAME}
        auth_password: ${PASSWORD}
        auth_identity: ${SMTP_USERNAME}
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
