name: documentation
on:
  workflow_dispatch:
    inputs:
      branch:
          description: 'Branch to run the workflow on'
          required: true
          default: 'main'

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python3 -m pip install mkdocs==1.6.1 mkdocstrings==0.29.0 "mkdocstrings[python]==0.29.0"

      # Deploy docs
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
